### ISSUE TITLE
Examples of using this and/or generated summaries?

### ISSUE THREAD

**Issue by Hellisotherpeople** [Shandilya21/SCTN-Sentence-Compression-through-Deletion-using-Stacked-LSTM#1]
I'd love to give this repo a try, but there are no instructions or examples of generated summaries.

**Comment by Shandilya21** [comment]
Hi @Hellisotherpeople Thanks for showing interest in my work, I am working towards updating my GitHub repositories. I will complete it soon. I will publish the readme.md with examples of instructions soon.

Thanks
Arunav
